### ISSUE TITLE
numeric != bitwise comparison

### ISSUE THREAD

**Issue by HellGL** [PhilippMuenzel/PPL#12]
Hi Philip,
I think you should not do
https://github.com/PhilippMuenzel/PPL/blob/47f758019bc769293e74b67476fd3ea7cbc93830/src/dataref.cpp#L133
`XPLMGetDataRefTypes(m_data_ref)` is an enum with [0,1,2,4,8,16,32]
and 
`(xplmType_Float | xplmType_Double)` is always 6

Why don't you just write 
`XPLMGetDataRefTypes(m_data_ref) != xplmType_Double` ?

**Comment by PhilippMuenzel** [comment]
That is how X-Plane works. All datarefs that provide double values also provide float values. You could construct a custom dataref that provided only doubles and failed on reading as float. But that would go against what X-Plane has done since version 6, so it'd be astonishing at least. See also https://developer.x-plane.com/sdk/XPLMDataTypeID/

**Comment by HellGL** [comment]
Hi Philip,  https://developer.x-plane.com/sdk/XPLMDataTypeID/ only give the types but you are probably right. But have you ever tried to register a double dataref with this code? It will always fail! I just wanted to say that you either need to do
`if ( XPLMGetDataRefTypes(m_data_ref) != xplmType_Float && XPLMGetDataRefTypes(m_data_ref) != xplmType_Double) )`
or 
`if ( !(XPLMGetDataRefTypes(m_data_ref) & (xplmType_Float | xplmType_Double)) )`

**Comment by HellGL** [comment]
Things have changed: sim/cockpit2/tcas/targets/position/double/* are defined as xplmType_Double only.
